# Generated by Django 2.1.3 on 2019-01-02 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0002_auto_20190102_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='perfil',
        ),
        migrations.AlterField(
            model_name='post',
            name='timeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='perfis.Perfil'),
        ),
        migrations.DeleteModel(
            name='Timeline',
        ),
    ]
