# Generated by Django 2.1.4 on 2019-01-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0003_auto_20190102_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
