<<<<<<< HEAD
# Generated by Django 2.1.3 on 2019-01-08 12:52
=======
# Generated by Django 2.1.3 on 2019-01-08 23:23
>>>>>>> 31aed2b4c36322ea5a19b48ce3fb42eb90e6cf7c

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0004_perfil_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='bloq',
<<<<<<< HEAD
            field=models.ManyToManyField(related_name='bloqueado', to='perfis.Perfil'),
=======
            field=models.ManyToManyField(blank=True, null=True, related_name='bloqueado', to='perfis.Perfil'),
>>>>>>> 31aed2b4c36322ea5a19b48ce3fb42eb90e6cf7c
        ),
    ]
