# Generated by Django 2.1.3 on 2019-01-21 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0005_perfil_bloq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ativo', models.BooleanField()),
                ('justificativa', models.CharField(max_length=256)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perfis.Perfil')),
            ],
        ),
    ]
