# Generated by Django 2.1.3 on 2019-01-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0008_post_photo_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo_post',
            field=models.ImageField(blank=True, upload_to='profile_img'),
        ),
    ]
