# Generated by Django 2.1.3 on 2019-01-28 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0011_auto_20190126_1759'),
        ('perfis', '0006_auto_20190108_2003'),
    ]

    operations = [
    ]
