# Generated by Django 2.1.3 on 2019-02-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0013_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='dinheiro',
            field=models.FloatField(default=0),
        ),
    ]
